### ISSUE TITLE
Passing a JSON array via the CLI seems broken

### ISSUE THREAD

**Issue by shawninder** [vigour-io/config#16]
This kind of thing used to be possible: `bin --prop '["list","of","values"]'` but no longer works, which breaks vigour-ferry, packer-server, vigour-shutter, vigour-test, vigour-wrapper and more

This issue covers:

1. Fixing the issue
2. Writing a test for it (to avoid people from breaking it again)

**Comment by shawninder** [comment]
This is the line where things break: https://github.com/vigour-io/config/blob/master/lib/constructor.js#L82 Before this line, the JSON array looks fine, but after this line, it is no longer fine.

**Comment by marcusbesjes** [comment]
published  `vigour-config@1.0.4`. 
problem was [the wrong variable was used for the check to see if val is a primitive](https://github.com/vigour-io/config/commit/8bc5c28566beef97588574843c4c0b495a056b3f#diff-2c64ac6ef1cec13b28a308b488c1f5c6L53) (to accomodate for lodash merge)

I didn't fix te tests yet, @shawninder could you link me to the repo that shows how to do testing?

**Comment by marcusbesjes** [comment]
testing guide: https://github.com/vigour-io/tooling/tree/master/testing
