### ISSUE TITLE
Dependency on deprecated `vigour-util/merge`

### ISSUE THREAD

**Issue by tvervest** [vigour-io/config#7]
When using the config package I get repeated errors in my terminal stating ``WARNING: `vigour-util/merge` is deprecated, consider using `lodash.merge` instead`` as set up by @shawninder in vigour-io/util#4.

**Comment by tvervest** [comment]
@marcusbesjes could you verify the fix and if it's OK merge and publish?

**Comment by DanilloCorvalan** [comment]
the same here :)

**Comment by jimdebeer** [comment]
@marcusbesjes can you replace util/merge /w lodash.merge? this warning is correct -- at util v2.0.0 the merge will be deprecated

**Comment by jimdebeer** [comment]
Allready fixed! nice

**Comment by marcusbesjes** [comment]
https://github.com/vigour-io/config/pull/10
